package org.xjy.jadmin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJadminUser<M extends BaseJadminUser<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setProjectCode(String projectCode) {
		set("projectCode", projectCode);
	}

	public String getProjectCode() {
		return get("projectCode");
	}

	public void setUserName(String userName) {
		set("userName", userName);
	}

	public String getUserName() {
		return get("userName");
	}

	public void setPassWord(String passWord) {
		set("passWord", passWord);
	}

	public String getPassWord() {
		return get("passWord");
	}

	public void setRealName(String realName) {
		set("realName", realName);
	}

	public String getRealName() {
		return get("realName");
	}

	public void setMobile(String mobile) {
		set("mobile", mobile);
	}

	public String getMobile() {
		return get("mobile");
	}

	public void setMenuIds(String menuIds) {
		set("menuIds", menuIds);
	}

	public String getMenuIds() {
		return get("menuIds");
	}

	public void setIsEnable(Integer isEnable) {
		set("isEnable", isEnable);
	}

	public Integer getIsEnable() {
		return get("isEnable");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
