package org.xjy.jadmin.model;

import com.jfinal.plugin.activerecord.Page;
import com.xiaoleilu.hutool.util.StrUtil;
import org.xjy.jadmin.model.base.BaseJadminProject;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JadminProject extends BaseJadminProject<JadminProject> {
    public static final JadminProject dao = new JadminProject().dao();

    public JadminProject findByCode(String code) {
        return dao.findFirst("select * from jadmin_project where code = ?", code);
    }

    public Page<JadminProject> findProjectPage(String code, int pageNo, int pageSize) {
        String sql = " from jadmin_project where isEnable = 1 ";
        if (StrUtil.isNotBlank(code))
            sql += " and code like '%" + code + "%'";
        return dao.paginate(pageNo, pageSize, "select *", sql);
    }

    public List<JadminProject> findProjectList() {
        return dao.find("select * from jadmin_project where isEnable = 1");
    }
}
