package org.xjy.jadmin.auth.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.xiaoleilu.hutool.util.StrUtil;
import org.xjy.jadmin.auth.model.base.BaseJadminUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JadminUser extends BaseJadminUser<JadminUser> {
    public static final JadminUser dao = new JadminUser().dao();

    public JadminUser findUser(String projectCode, String username) {
        return dao.findFirst("select * from jadmin_user where projectCode = ? and userName = ?", projectCode, username);
    }

    public Page<JadminUser> findUserList(String projectCode, String username, int pageNo, int pageSize) {
        String sql = " from jadmin_user where isEnable = 1 ";
        if (StrUtil.isBlank(projectCode))
            sql += " and projectCode = '0'";
        if (StrUtil.isNotBlank(projectCode))
            sql += " and projectCode = '" + projectCode + "'";
        if (StrUtil.isNotBlank(username))
            sql += " and username like '%" + username + "%'";
        return dao.paginate(pageNo, pageSize, "select * ", sql);
    }

    public static void removeMenuId(long menuId) {
        String sql = "update jadmin_user set `menuIds` = replace(menuIds,'," + menuId + ",',',')";
        Db.update(sql);
    }
}
