package org.xjy.jadmin.auth.model;

import org.xjy.jadmin.auth.model.base.BaseJadminMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JadminMenu extends BaseJadminMenu<JadminMenu> {
	public static final JadminMenu dao = new JadminMenu().dao();
}
