package org.xjy.jadmin.auth.model;

import org.xjy.jadmin.auth.model.base.BaseJadminUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JadminUser extends BaseJadminUser<JadminUser> {
	public static final JadminUser dao = new JadminUser().dao();
}
