package org.xjy.jadmin.auth.model;

import org.xjy.jadmin.auth.model.base.BaseJadminProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JadminProject extends BaseJadminProject<JadminProject> {
	public static final JadminProject dao = new JadminProject().dao();
}
